### ISSUE TITLE
_.uuid is not a function

### ISSUE THREAD

**Issue by IbrahimHd** [tybeck/pure-angular-advanced-searchbox#1]
Hi tybeck, 
Thank you for the great work you are doing with this awesome search box.

I'm using Visual Studio and I'm trying to install the dependencies
**lodash.js** (from http://lodash.com) & **lodash-mix.js** (from [this repository](https://github.com/tapatron/lodash-mix))
The function under subject **_.uuid()** is exist in lodash-mix.js:
`extendWith.uuid = function () {...}` but it is not detected by paasbSearchBox.

Is there something needs to be injected?

**Comment by tybeck** [comment]
Thanks!

I'm trying to drop the dependencies right now actually; I should have this fixed today.

Tyler

**Comment by tybeck** [comment]
I've removed the dependency on **lodash-mix**; the only dependencies now should be **lodash** and **angular**.

Thanks,
Tyler

**Comment by IbrahimHd** [comment]
Many thanks Tyler!
