### ISSUE TITLE
Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by IbrahimHd** [tybeck/pure-angular-advanced-searchbox#2]
Hi Tyler,

The directive **paasbSearchBox** gives an error on the **store** property in this piece of code:
`$scope.paasbSearchBoxConfig.store) ? true : false;`

Thanks for your effort.

**Comment by tybeck** [comment]
I can see where this could be an issue; thanks for pointing it out; I wasn't able to replicate it, but it shouldn't be thrown anymore.

**Comment by IbrahimHd** [comment]
this error is no longer appearing starting from version 1.1.69
