### ISSUE TITLE
Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by IbrahimHd** [tybeck/pure-angular-advanced-searchbox#3]
Function _getParentByAttribute_ in factory _paasbUtils_ gives an error on the **nodeName** property in this piece of code:
`var nName = target[0].nodeName.toLowerCase();`

Thanks

**Comment by tybeck** [comment]
Could you provide some more information on where this broke? I haven't seen this thrown, maybe I just haven't configured it the same, but I have thrown an extra check to break out incase no target is available.

Thanks for your help!

**Comment by IbrahimHd** [comment]
this error is no longer appearing starting from version 1.1.69
