### ISSUE TITLE
Filter Suggested Values

### ISSUE THREAD

**Issue by IbrahimHd** [tybeck/pure-angular-advanced-searchbox#5]
Hi Tyler,

I'm getting an error when I try to use **suggestedValues** property of the _paasb-search-box-filtering_ attribute in both cases, as an URL or Array of strings. My inputs are like this:
'suggestedValues': "http://localhost:27254/api/getData"
'suggestedValues': "['A', 'B', 'C', 'D']"
The error message says:  **Unknown provider: suggestFilterProvider <- suggestFilter**
Thank you in advance!

**Comment by tybeck** [comment]
I'll check this out.

Thanks!

**Comment by tybeck** [comment]
This has been fixed.  Please let me know if you see issues still. **v1.1.77**

**Comment by IbrahimHd** [comment]
It works fine now. 
Thanks Tyler!
