### ISSUE TITLE
Configuration of autoSuggestions

### ISSUE THREAD

**Issue by IbrahimHd** [tybeck/pure-angular-advanced-searchbox#7]
Hi again!

I noticed that the **autoSuggestions** feature is not documented in the ReadMe.
I skimmed through the code to figure out what properties are available, I found _plainTerm_, _term_, & _suggestedCount_.
Below is my attempt providing the following in the _Options_:

```
'showSuggestions': true,
'autoSuggestions':[{'plainTerm':'Mytest1',
                    'term': 'test1',
                    'suggestedCount':44}]
```

But unfortunately nothing appears in the "most popular suggestions" menu.
Am I missing something?
Thank you for your help!

**Comment by tybeck** [comment]
Hey there,

Your looking at the **auto-complete** feature; the auto-suggest feature is for **suggestedValues**, which gives you the ability to suggest values to filters and restrict them with **restrictedSuggestedValues**. 

**auto-complete** takes a URL via **autoCompleteUrl** via an API service that will then populate the "most popular suggestions" menu; this may need some refinement though; I will relook at this, if you have any suggestions I'll be open to them as well!

Thanks, sorry for the late response.

**Comment by IbrahimHd** [comment]
Thanks Tyler for clarification.
**autoSuggestions** is for **filters** and it takes _array of strings_ but **not URL**, like this:
`'suggestedValues':['Male', 'Female']`
